project:
  type: website

website:
  repo-url: https://github.com/kedington27/Mapping-Spatial-Networks-of-Queer-Pleasure-Within-New-York-City
  repo-actions: [issue]
  sidebar:
    style: docked
    search: true
    align: center
    tools:
      - icon: house-fill
        href: index.qmd
      - icon: github
        href: https://github.com/kedington27/Mapping-Spatial-Networks-of-Queer-Pleasure-Within-New-York-City
    contents: 
      - href: index.qmd
        text: Mapping Spatial Networks of Queer Pleasure Within New York City
      - href: background.qmd
        text: Background~ Stonewall & Gay Liberation
      - href: liquor-gay.qmd
        text: Liquor Licensing as Discrimination
      - href: cabarets.qmd
        text: Cabaret Licensing as Discrimination
      - href: AIDS.qmd
        text: AIDS and Public Sex~ Debates on Sex Establishments
      - href: further-readings.qmd
        text: Sources for Further Reading
      - href: about.qmd
      - href: another_page.qmd
        text: Contributor
  comments: 
    giscus: 
      repo: kedington27/Mapping-Spatial-Networks-of-Queer-Pleasure-Within-New-York-City
      category: General
      mapping: title
      theme: 
        dark: dark_protanopia

format:
  html:
    theme: 
      - darkly
      - custom.scss
    mainfont: "Comic Sans"
    toc: true



