project:
  type: website

website:
  title: "website"
  sidebar:
    style: docked
    contents: 
      - href: index.qmd
        text: Mapping Spatial Networks of Queer Pleasure Within New York City
      - href: about.qmd
      - href: another_page.qmd
        text: Contributor

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



