project:
  type: website

website:
  title: "website"
  sidebar:
    style: docked
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



