project:
  type: website

website:
  title: "website"
  sidebar:
    style: docked
    contents: 
      - href: index.qmd
        text: Mapping Spatial Networks of Queer Pleasure Within New York City
      - href: about.qmd
      - href: another_page.qmd
        text: Contributor
      - href: brooklyn-map.qmd
        text: Brooklyn Map

format:
  html:
    theme: 
      - darkly
      - custom.scss
    mainfont: "Comic Sans"
    css: styles.css
    toc: true



