project:
  type: website

website:
  title: "website"
  sidebar:
    style: docked
    contents: 
      - href: index.qmd
        text: Mapping Spatial Networks of Queer Pleasure Within New York City
      - href: about.qmd
      - href: another_page.qmd
        text: Contributor
      - href: liquor-gay.qmd
        text: Liquor Licensing as Discrimination
      - href: cabarets.qmd
        text: Cabaret Licensing as Discrimination
      - href: AIDS.qmd
        text: AIDS and Public Sex: Debates on Sex Establishments
      - href: background.qmd
        text: Background: Stonewall & 1970s Gay Liberation

format:
  html:
    theme: 
      - darkly
      - custom.scss
    mainfont: "Comic Sans"
    css: styles.css
    toc: true



