---
title: "About"
editor: 
  markdown: 
    wrap: 72
---

This webpage serves as the second part of my MA portfolio project. In
its current form, it is the beginning of the final project. This is a
website that will trace the history of queer spatial geography in New
York City from the 1970s until 1986. I am interested in analyzing the
locations of what Fiona Buckland called "third spaces" for queer people,
especially gay bars, clubs, bathhouses, bookstores, cinemas,
restaurants, sex stores, backrooms, and cruising locations.

The map and the companion text-based pages are an extension of my
paper's argument that safer sex education during AIDS was negotiated,
contested, and implemented in public queer spaces by queer actors. It
further visually supports and provides context for the acts of
discrimination and general public health debates that impacted queer
communities and establishments before and during AIDS. It visually
argues that the government was both slow to shut down bathhouses and
backrooms during AIDS and that it continued to use tactics of licensing
and rezoning to discriminate against the queer community before, during,
and after the peak of AIDS.

In its final form, the website will trace the openings, closings, and
relocating or negotiations occurring within the city at the time to show
the attempts by the dominant society to limit queer spaces,
representation, and culture. It does this via mapping and adding
descriptions of the establishments.

This project took influence and hopes to contribute to the ongoing
mapping efforts by other sites like <https://www.queermaps.org/about>
and <https://www.nyclgbtsites.org/theme/bars-nightlife/>.

# Acknowledgments

Since this is my first major project as a high-level historian, I would
like to extend my thanks to everyone who helped make it a success.
First, I would like to thank my committee members Dennis Halpin, Amanda
Demmer, and Marian Mollin for believing in me and my concept for this
website despite knowing very little about coding and web design, for
continuing to work with me, and for pushing me to always improve and
never settle.

Next, I would like to thank the New York Public Library Archive, the
Center's archive, and the NYU Archive for allowing me to conduct all of
my primary source research and for having the most helpful and
accommodating archivists who helped me from day one until publishing
this website.

Thank you to Jesse Sadler for the countless meetings, code writing
sessions, and teaching the digital history class that made me feel
confident enough to pitch coding my own website from scratch. Without
his help and willingness to answer my endless questions about errors,
issues, and ideas, this project would look nothing like it does today.
He will forever be the honorary fourth member of my graduate committee.

Finally, a big thanks go to long list of friends in the department and
outside of it who have helped read and edit the website and just
listened to me complain in times where I was struggling and who were
also there to celebrate each small victory. So, in no particular order,
thank you to Kay, Hannah, Paige, Miles, Mason, Garrett, Kayla, Hunter,
and Talia. Thank you to my mom, Trisha, who traveled to New York City
with me so I did not have to travel alone. Your company was greatly
appreciated, and your food choices were always on point and needed after
a full day at the archive. To my dad Royce, thank you for listening to
my coding problems every time I went home, and thank you to my younger
brother Carson for providing silent support from Massachusetts. I love
you all so much!

To my partner Kyler thank you for putting up with me and my endless
discussions about queer establishments in New York City and the various
other topics that continuously came up during my research and writing. I
know you never wanted to become an expert in any of these topics yet you
always listened and assured me they were interesting. Thank you for your
help with my Excel sheets, you are a much better coder than I am on that
software! The many nights we spent together going through my locations
by hand to create the map were both time consuming but more bearable
with your assistance and silly nature. Lastly, thank you for always
listening to my rants and comforting me when I thought that this project
was a terrible idea. I love you and hope you will continue to be by my
side for all my future crazy endeavors.

You all helped me stay sane or at least offered to listen to my problems
and appear somewhat interested in them! To anyone I missed, it was not
intentional. I have greatly appreciated everyone's help on this project,
no matter how large or small the contribution appeared, so thank you!

# 
