---
title: "Background: Stonewall & 1970s Gay Liberation"
---
## Before Stonewall: A Brief recounting of American Queer History

  - Chauncey's fairies, wolves and other "gays" starting in 1890's NYC
  - John D'Emilio, Hirshman, and Johnson's Mattachine Society (the first homosexual
  political organization in the United States that started in the 1950s)
  - Linking it back to the liquor and cabaret licenses pages as an intro to
  the Mafia's ownership of gay bars within the city due to Prohibition and crime
  - Overall key point is that gay life in the US does not start with Stonewall
  it just hits a new era of openness.

## Stonewall 1969

- Telling the narrative of Stonewall through use of primary and secondary
source material in a decent amount of detail since it is one of the biggest
moments that is associated with the start of gay liberation.

## 1970s = Welcome to Gay Liberation

  - Defining the core ideas of gay liberation and how they were political,
sexual, social, and based in consumerism

  - Provide a few narratives to demonstrate the "themes" of the 1970s that
focus on sexual culture, queer establishments increased visibility, and
political activism within the queer community.

## 1980s: AIDS and Impact of the Liberation Spirit

- How does this shift in the 1970s impact the AIDS crisis of the 1980s? Answer
using Shilts, documents on sexual "promiscuity" and sexual habits, Larry 
Kramer's books from the 1970s, and political documents (ACT UP)

*Try to add in photos throughout the page* 