---
title: "Cabaret Licensing as Discrimination"
editor: 
  markdown: 
    wrap: 72
---

## What is a Cabaret License?

-   Defining a Cabaret License

    -   A cabaret license is a license for a place that sells food and
        drink while having an orchestra or any type of live
        entertainment, or where dancing is permitted. The license
        provides permission for the business to operate with live music,
        dancing, and drinking.[^1]

-   How does it connect to LGBTQ discrimination in New York City/within
    the US?

    -   Use Chauncey and Buckland

-   An example/story about the use of this type of regulation quoted
    from George Chauncey, Fiona Buckland or from a newspaper article or
    other primary sources

    -   Need to find this

-   How did queer establishments get around this restriction? How was it
    enforced within New York?

    -   And this

-   Is this type of regulation still around today?

    -   Not in NYC as of 2017 the city repealed the Cabaret Licensing
        Law that had been enacted under Prohibition so now there is no
        need for establishments to go through the process of obtaining a
        cabaret permit in order to have live music or dancing while also
        selling drinks.

-   How do gay men remember this type of restriction and its impact on
    their feelings of safety or access to community?

    -   Need to find this in my sources

[^1]: LawInsider, “Cabaret License Definition \| Law Insider,” Law
    Insider, 2024,
    <https://www.lawinsider.com/dictionary/cabaret-license>.
