---
title: "Further Readings"
---

For more information on the topics mentioned briefly in this webpage please feel free to consult from these curated book lists. I used many of these works in my historiography exams and they serve as guiding influences on the content of this website!

## Reading List on Homosexuality, Pleasure Culture, and Urban Nightlife in America

Bronski, Michael. A Queer History of the United States. Boston: Beacon, 2011.

Buckland, Fiona. Impossible Dance: Club Culture and Queer World-Making. Middletown, Conn.: Wesleyan University Press, 2002.

Canaday, Margot. The Straight State: Sexuality and Citizenship in Twentieth-Century America. Princeton, N.J.; Woodstock: Princeton University Press, 2011.

CapóJulio. Welcome to Fairyland: Queer Miami before 1940. Chapel Hill: University of North Carolina Press, 2017.

Certeau, Michel de. “Walking in the City.” In The Practice of Everyday Life. Berkeley: University of California Press, 1984.

Chauncey, George. Gay New York: Gender, Urban Culture, and the Making of the Gay Male World, 1890-1940. New York: Basic Books, 1994.

D’emilio, John. Sexual Politics, Sexual Communities: The Making of a Homosexual Minority in the United States, 1940-70. Chicago: University Of Chicago P, 1983.

D’emilio, John, and Estelle B Freedman. Intimate Matters: A History of Sexuality in America. New York: Harper & Row, 1988.

Echols, Alice. Hot Stuff: Disco and the Remaking of American Culture. New York: Norton, 2011.

Enstadt, Nan. Ladies of Labor, Girls of Adventure: Working Women, Popular Culture, and Labor Politics at the Turn of the Century. New York: Columbia University Press, Cop, 1999.

Heap, Chad C. Slumming: Sexual and Racial Encounters in American Nightlife, 1885-1940. Chicago: Univ. Of Chicago Press, 2010.

Hilderbrand, Lucas. “A Suitcase Full of Vaseline, or Travels in the 1970s Gay World.” Journal of the History of Sexuality 22, no. 3 (September 2013): 373–402. https://doi.org/10.7560/jhs22301.

———. The Bars Are Ours: Histories and Cultures of Gay Bars in America, 1960 and After. Duke University Press, 2023.

Hirshman, Linda R. Victory: The Triumphant Gay Revolution. New York: Harper, 2017.

Johnson, David K. BUYING GAY: How Physique Entrepreneurs Sparked a Movement. Columbia University Press, 2021.

———. The Lavender Scare: The Cold War Persecution of Gays and Lesbians in the Federal Government. Chicago, Ill.: University of Chicago Press, 2004.

Keire, Mara Laura. For Business and Pleasure: Red-Light Districts and the Regulation of Vice in the United States 1890-1933. JHU Press, 2010.

Lyons, Clare A. Sex among the Rabble: An Intimate History of Gender & Power in the Age of Revolution, Philadelphia, 1730-1830. UNC Press Books, 2012.

Stein, Marc. City of Sisterly and Brotherly Loves: Lesbian and Gay Philadelphia, 1945-1972. Philadelphia: Temple University Press, 2004.

Zmith, Adam. Deep Sniff: A History of Poppers and Queer Futures. London: Watkins Media Limited, 2021.

## Reading List on AIDS, Politics, and the 1980s

Brier, Jennifer. Infectious Ideas: U.S. Political Responses to the AIDS Crisis. Chapel Hill N.C.: University Of North Carolina Press, 2009.

Chambré, Susan Maizel . Fighting for Our Lives: New York’s AIDS Community and the Politics of Disease. Rutgers University Press, 2006.

Collier, Aine. The Humble Little Condom. Prometheus Books, 2007.

Colter, Ephen Glenn, and Dangerous Bedfellows. Policing Public Sex: Queer Politics and the Future of AIDS Activism. South End, 1997.

Dean, Tim. Unlimited Intimacy: Reflections on the Subculture of Barebacking. Chicago: University of Chicago Press, 2009.

Duggan, Lisa, and Nan D Hunter. Sex Wars: Sexual Dissent and Political Culture. New York: Routledge, 2006.

Epstein, Steven. Impure Science: AIDS, Activism, and the Politics of Knowledge. Berkeley, Calif. Univ. Of California Press \[20\]09, 1996.

Escoffier, Jeffrey. “Sex, Safety, and the Trauma of AIDS.” WSQ: Women’s Studies Quarterly 39, no. 1-2 (2011): 129–38. https://doi.org/10.1353/wsq.2011.0029.

France, David. How to Survive a Plague: The Story of How Activists and Scientists Tamed AIDS. New York: Vintage Books, 2017.

Gamson, J. “Rubber Wars: Struggles over the Condom in the United States.” PubMed 1, no. 2 (October 1, 1990): 262–82.

Haus, Sebastian. “Risky Sex - Risky Language: HIV/AIDS and the West German Gay Scene in the 1980s.” Historical Social Research 41, no. 1 (January 1, 2016): 111–34. https://doi.org/10.12759/hsr.41.2016.1.111-134.

Lauritsen, John, and Ian Young. The AIDS Cult: Essays on the Gay Health Crisis. Provincetown, Ma: Askleopios, 1997.

Lord, Alexandra. Condom Nation: The U.S. Government’s Sex Education Campaign from World War I to the Internet. Johns Hopkins University Press, 2010.

Moskowitz, David A., and Michael E. Roloff. “The Existence of a Bug Chasing Subculture.” Culture, Health & Sexuality 9, no. 4 (July 2007): 347–57. https://doi.org/10.1080/13691050600976296.

PARKER, RICHARD. “Grassroots Activism, Civil Society Mobilization, and the Politics of the Global HIV/AIDS Epidemic.” The Brown Journal of World Affairs 17, no. 2 (2011): 21–37. http://www.jstor.org/stable/24590789.

Patton, Cindy. Sex & Germs: The Politics of AIDS. Montreal; New York: Black Rose Books, Cop, 1986.

Perrow, Charles, and GuillénMauro F. The AIDS Disaster: The Failure of Organizations in New York and the Nation. New Haven, Conn.: Yale University Press, 1990.

Rossinow, Douglas C. The Reagan Era: A History of the 1980s. New York: Columbia University Press, 2017.

Schulman, Sarah. Let the Record Show: A Political History of ACT up New York, 1987-1993. New York: Farrar, Straus And Giroux, 2021.

Shernoff, Michael. Without Condoms: Unprotected Sex, Gay Men&Barebacking. Taylor & Francis, 2005.

Shilts, Randy. And the Band Played On: Politics, People, and the AIDS Epidemic. New York: St. Martin’s Press, 1987.

Zelizer, Julian E, and Bruce J Schulman. Rightward Bound: Making America Conservative in the 1970’S. Cambridge, MA; London: Harvard University Press, 2008.
