---
title: "Mapping Spatial Networks of Queer Pleasure Within New York City"
---

(Start by adding an introduction line to the map)

(map goes on this page)

(Below the map have the various locations listed with their open and close dates and any other information I have on them so far)

Bars and Clubs:

1.  Bar Room 432/Mother: 432 West 14th Street, Meatpacking District. It was known as Bar Room 432 from 1990 until 1996. In 1996 it was reopened as Mother until it closed its doors in 2000.
2.  Blue's: 264 West 43rd Street, Theater District. It was a Black gay bar that was most famous for the raid the police conducted on the establishment in 1982.
3.  Boots and Saddle: formerly on Christopher Street then it moved to 100A 7th Avenue South, West Village. This gay bar opened in 1974 on Christopher Street but due to rent increases moved to its final location in 2015. In 2018 the bar closed due to unknown reasons.
4.  Boy Bar: 15th St. Marks Place, East Village
5.  Café con Leche, Club Expo/Kat Klub: 124 West 43rd Street, Mid-Town Manhattan
6.  Chi Chiz: 135 Christopher Street (between Greenwich and Hudson), Greenwich Village
7.  Club 82: 82 East 4th Street, East Village
8.  Club Fahrenheit: 349 Broadway (Leonard St.), Tribeca
9.  Crazy Nanny's: 21 Seventh Ave (Leroy St.), West Village
10. Cubby Hole/Henrietta Hudson: 438-444 Hudson Street, Greenwich Village
11. Cubbyhole: 281 West 12th Street, Greenwich Village
12. David Manscuso Residence/The Loft: 645-547 Broadway, Greenwich Village
13. Duchess/Grove/Pandora's Box: 70 Grove Street, Greenwich Village
14. la Escuelita: 301 West 39th Street (8th Avenue) Mid-town Manhattan
15. Flamingo East: 219 Second Avenue (13th Street) East Village
16. Foxy/Velvet: 167 Avenue A (10th Street), East Village
17. Julius': 159 West 10th Street, Greenwich Village
18. Kooky's: 149 West 14th Street, Chelsea
19. Life: 158 Bleecker Street, Greenwich Village
20. Limelight: 47 West 20th Street, Chelsea
21. Meow Mix: 269 East Houston Street (Suffolk St.), East Village
22. Ninth Circle: 169 West 10th Street, Greenwich Village
23. Paradise Garage: 84 King Street, Greenwich Village
24. Pieces: 8 Christopher Street, Greenwich Village
25. Pompier Restaurant/Tenth of Always/Bonnie & Clyde: 82 West 3rd Street, Greenwich Village
26. Pyramid: 101 Ave A (6th St.), East Village
27. Ramrod: 394-395 West Street, Greenwich Village
28. Roxy: 515 West 18th Street, Chelsea
29. Splash: 50 West 17th Street (6th Ave), Chelsea
30. Don Hill's: 511 Greenwich St (Spring St.), Tribeca
31. Studio 54 (originally Gallo Opera House): 254 West 54th Street, Theater District
32. Suspect/Nowbar: 7th Avenue South (Leroy St.), West Village
33. The Anvil: 500 West 14th Street, Meatpacking District
34. The Barefoot Boy: 309 East 39th Street at Second Avenue, Hell's Kitchen?
35. The Candle Bar: 309 Amsterdam Avenue between West 74th & 75th Streets, Upper West Side
36. The Cock Ring: 180 Christopher Street at West Street, Greenwich Village
37. The International Stud: 733 Greenwich Street between Fourth Street & Waverly Place, West Village
38. The Mine Shaft: 835 Washington Street, Greenwich Village
39. The Monster: 80 Grove Street, Greenwich Village
40. The Saint: 105 Second Avenue, East Village
41. The Snake Pit: 215 West 10th Street, Greenwich Village
42. The Toilet: 400 West 14th Street, Meatpacking District
43. Townhouse: 236 East 58th Street, Midtown East
44. Tunnel: 220 12th Avenue, Chelsea
45. Twilo: 530 West 27th Street (10th Avenue), Chelsea
46. Uncle Charlie's: 56 Greenwich Avenue, Greenwich Village
47. Vinyl: 6 Hubert Street, Tribeca
