---
title: "Liquor Licensing as Discrimination"
editor: 
  markdown: 
    wrap: 72
---

## What is a Liquor License?

A liquor license is a permit issued by the government for businesses to
sell, manufacture, store, or otherwise use alcoholic beverages.[^1]

[^1]: “Liquor License,” Wikipedia, February 16, 2020,
    <https://en.wikipedia.org/wiki/Liquor_license>.

## How does it connect to LGBTQ discrimination in New York City/within the US?

New York Liquor Authority in the mid-1900s refused to issue permits to
places that homosexuals were known to congregate and if bars were found
to be homosexual hot spots their licenses would be removed and they
would often be raided.

Most New York gay bars before the 1970s were owned and operated by the
Mafia due to the discrimination by police and the liquor authorities.
Due to the underground, secretive, and crime-entangled nature of the
Mafia their ownership allowed gay bars to operate in relative secret
within the city, however their treatment of patrons and often strict
rules led to feelings of resentment from within the queer community as
the 1960s drew to a close.

-   An example/story about the use of this type of regulation quoted
    from George Chauncey or from a newspaper article

    -   Need to find this

        -   Look into Snake Pit Bar raid for a good story

## How did queer establishments get around this restriction? How was it enforced within New York?

```         
-   It was mostly through Mafia ownership and strict rules on
    patrons to ensure that things stayed socially acceptable within
    the bar and no one could "prove" it was a gay bar.
```

